### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by esginmurat** [Ademking/Iftar-Tunisia#1]
Hello. Thanks for this code. But not working.
After debug mode on my browser.
Chrome says; Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID https://kouki.website/timetunisia.php
Please help me.

**Comment by Ademking** [comment]
Hello @esginmurat 
This project contains frontend only. I did not include PHP code
Also, this project is very old. i hope i can find it for you.
Thanks
